-- 코드를 입력하세요
SELECT DATE_FORMAT(ONL.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
ONL.PRODUCT_ID, 
ONL.USER_ID, 
ONL.SALES_AMOUNT
FROM ONLINE_SALE ONL
WHERE YEAR(ONL.SALES_DATE) = 2022 
AND MONTH(ONL.SALES_DATE) = 3

UNION ALL 

SELECT 
    DATE_FORMAT(OFF.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    OFF.PRODUCT_ID, 
    NULL AS USER_ID, 
    OFF.SALES_AMOUNT
FROM OFFLINE_SALE OFF
WHERE YEAR(OFF.SALES_DATE) = 2022 
AND MONTH(OFF.SALES_DATE) = 3

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC