-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) as YEAR,
MONTH(o.SALES_DATE) as MONTH,
count(distinct u.USER_ID) as PURCHASED_USERS,
ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE joined LIKE '2021%'), 1) AS PUCHASED_RATIO
from ONLINE_SALE o
join USER_INFO u on u.USER_ID = o.USER_ID
where u.JOINED between '2021-01-01' and '2021-12-31'
group by YEAR, MONTH
order by YEAR, MONTH


