SELECT FI.ID, FN.FISH_NAME, FI.LENGTH 
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT MAX(FI_SUB.LENGTH) 
    FROM FISH_INFO FI_SUB
    WHERE FN.FISH_TYPE = FI_SUB.FISH_TYPE
    
)
ORDER BY FI.ID ASC;
